org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

version=1.3.6
group=com.sillyprootsoda.villagernews

fabric_api_version=0.160.7+26.3
emf_version=kdDVwkgV
etf_version=Hs3N31ud
esf_version=wLbaCWaA
modmenu_version=21.0.0-beta.1

dialogue_test_command=false

neoforge_moddev_version=2.0.147
neoforge_version=26.3.0.7-beta
