models.1=2
name.1=iregex:(Mayor|Mayor Villager|The Mayor)
models.2=3
name.2=iregex:(Testificate Man)
models.3=4
name.3=iregex:(Villager Number 5|Villager #5)
models.4=5
name.4=iregex:(Villager Number 9|Villager #9)
models.5=6
name.5=iregex:(Villager Unreachable|Can't Catch Me!)
models.6=1
name.6=iregex:.*
